### PR TITLE
Added theming

### PR DESCRIPTION
**Pull request by 101hawn**

### CODE REVIEW

**Comment by SlightlySwissGuy** [comment]
This intermittently crashes (every few times it is run) with the output:
4 8

And stacktrace:

Exception in thread "main" java.lang.IllegalArgumentException: layoutState cannot be null
	at com.intellij.uiDesigner.core.DimensionInfo.<init>(DimensionInfo.java:36)
	at com.intellij.uiDesigner.core.VerticalInfo.<init>(VerticalInfo.java:20)
	at com.intellij.uiDesigner.core.GridLayoutManager.validateInfos(GridLayoutManager.java:585)
	at com.intellij.uiDesigner.core.GridLayoutManager.layoutContainer(GridLayoutManager.java:392)
	at java.awt.Container.layout(Container.java:1512)
	at java.awt.Container.doLayout(Container.java:1501)
	at java.awt.Container.validateTree(Container.java:1697)
	at java.awt.Container.validateTree(Container.java:1706)
	at java.awt.Container.validateTree(Container.java:1706)
	at java.awt.Container.validateTree(Container.java:1706)
	at java.awt.Container.validateTree(Container.java:1706)
	at java.awt.Container.validate(Container.java:1632)
	at java.awt.Container.validateUnconditionally(Container.java:1669)
	at java.awt.Window.show(Window.java:1033)
	at java.awt.Component.show(Component.java:1671)
	at java.awt.Component.setVisible(Component.java:1623)
	at java.awt.Window.setVisible(Window.java:1014)
	at uk.ac.cam.groupseven.weatherapp.MainForm.main(MainForm.java:21)

Any idea why this is happening?
(line 21 is frame.setVisible(true) )

**Comment by SlightlySwissGuy** [comment]
I have run the program repeatedly and generated a 'bitstream' of it working vs not working (1 if it worked, 0 if it crashed)
This is what I got:
111111011011101110101110100011111110111100111101
This looks random to me, suggesting a concurrency issue

**Comment by 101hawn** [comment]
Bug present in develop branch as well. #12

**Comment by SlightlySwissGuy** [comment]
I haven't been able to reproduce it in develop but maybe

**Comment by SlightlySwissGuy** [comment]
Ah yep, found it in develop

**Pull request merged**
